
# EXTRA_LIBPATHS += -L $(SDKDIR)$(DELIM)..$(DELIM)examples$(DELIM)fmsound_utils
# EXTRA_LIBS += -lfmsndutils

include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

# BIN = libfmsndutils$(LIBEXT)

CSRCS = fmsound_nxaudio.c operator_algorithm.c

include $(APPDIR)/Application.mk
